version: '3'
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 2717:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  frontend: #This is the name of our Nextjs application.
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: dev #command to execute
    ports:
      - '3000:3000'
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next